### ISSUE TITLE
login flow throws error saying - role-id cannot be null

### ISSUE THREAD

**Issue by exexzian** [oojorgeoo89/QuizZz#1]

**Comment by oojorgeoo89** [comment]
Hi Exexzian!

Thank you for the feedback. There was an issue with the database data initialisation after schema creation (the sql script wasn't getting called). Since this was in order to automatically pre-load a set of roles, and I ended up not using role based authorisation in the application, I've decided to remove the code related to roles altogether. 

The changes have been delivered to the master branch. Please, let me know whether this solves your problem :)

Jorge
