### ISSUE TITLE
Running app without smtp client

### ISSUE THREAD

**Issue by Nxtra** [oojorgeoo89/QuizZz#2]
I don't succeed in running the app without smtp client? 
How can I achieve this?

**Comment by oojorgeoo89** [comment]
Hi Nxtra!

If you don't want to use email login at all, you can use RegistrationServiceSimple instead of RegistrationServiceMail. I haven't defined any profile to achieve this, but you can easily tell the IoC container to use the Simple version of the service instead. For that, just remove the @Service annotation from RegistrationServiceMail and add it to RegistrationServiceSimple.

Good luck!
